Part 4: Reshape, Flatten, Ravel 
1. Create an array of numbers from 1–12. Reshape it into a (3×4) array. Then reshape it again into (2×6). 
2. Use .flatten() and .ravel() on a 2D array and show the difference between them when you modify the 
flattened and raveled array. 
3. Given an array: 
arr = np.arange(1, 10).reshape(3, 3) 
   - Convert it into a 1D array using both methods. 
   - Show if changes in one reflect in the original array.

In [105]:
import numpy as np

In [106]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [107]:
arr= arr.reshape(3,4)

In [108]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [109]:
arr = arr.reshape(2,6)

In [110]:
print(arr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [117]:
fal = arr.flatten()
fal[0] = 200

In [118]:
print(fal)

[200   2   3   4   5   6   7   8   9  10  11  12]


In [119]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [120]:
rave = arr.ravel()
rave[0] = 201

In [121]:
print(rave)

[201   2   3   4   5   6   7   8   9  10  11  12]


In [122]:
print(arr)

[[201   2   3   4   5   6]
 [  7   8   9  10  11  12]]


as you can see flatten work with copy thats mean original array will not effect
but in ravel oppossite of flatten its work on view original will effect

In [124]:
arr1 = np.arange(1, 10).reshape(3, 3) 

In [125]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [127]:
flate= arr1.flatten()
print(flate)

[1 2 3 4 5 6 7 8 9]


In [129]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [131]:
rav = arr1.ravel()
print(rav)

[1 2 3 4 5 6 7 8 9]


In [132]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
