Part 4: Vectorization 
1. Create two arrays A and B of 5 random integers each. Perform element-wise addition, subtraction, 
multiplication, and division without using loops. 
2. Using vectorization, compute the square root, exponential, and sine of all elements in a single array. 
[Hint: for computing using np.sqrt(), For computing use np.exp(), For Computing sine using np.sin()] 
3. Given a list of 10 temperatures in Celsius, convert them to Fahrenheit using a single vectorized 
expression. 
[Hint: for Celsius to Fahrenheit conversion use formula  °F = (°C × 9/5) + 32] 

In [54]:
import numpy as np

In [55]:
arr = np.array(np.random.randint(0,99, size= 5))

In [56]:
arr

array([ 6, 68, 12, 16, 45], dtype=int32)

In [57]:
arr +5

array([11, 73, 17, 21, 50], dtype=int32)

In [58]:
arr -5

array([ 1, 63,  7, 11, 40], dtype=int32)

In [59]:
arr * 5

array([ 30, 340,  60,  80, 225], dtype=int32)

In [60]:
arr / 5

array([ 1.2, 13.6,  2.4,  3.2,  9. ])

In [61]:
np.sqrt(arr)

array([2.44948974, 8.24621125, 3.46410162, 4.        , 6.70820393])

In [62]:
np.sin(arr)

array([-0.2794155 , -0.89792768, -0.53657292, -0.28790332,  0.85090352])

In [63]:
np.exp(arr)

array([4.03428793e+02, 3.40427605e+29, 1.62754791e+05, 8.88611052e+06,
       3.49342711e+19])

In [64]:
# make temperature list in numPy say array

temp = np.array(np.random.randint(5,25, size=10))  #make array in whch value in random 1 to 10 will be int32
temp

f = temp * 9/5 +32

In [65]:
f

array([46.4, 57.2, 46.4, 64.4, 68. , 66.2, 44.6, 69.8, 66.2, 44.6])