Part 4: Broadcasting 
1. Create a 3×3 matrix – named as A and: 
   - Add 10 to it (scalar broadcasting). 
   - Add a row vector [1, 2, 3] to it (row broadcasting). 
   - Add a column vector [[1], [2], [3]] to it (column broadcasting). 
2. Predict the shape of each result before executing the code. 

In [30]:
import numpy as np

In [31]:
A = mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [ ]:
A = mat + 10

# predict : 
# 
# [[10,12,13],
# [14,15,16],
# 17,18,19]

In [ ]:
row = np.array([1,2,3])

A = mat + row

# sahpe of A (3,3)
# shape of row (3,1)

# so numpy broadcast of   [1,2,3],
#                         [1,2,3]
#                         [1,2,3]
# Result:
#     [[ 2,4,6],
#     [ 5,7,9],
#     [ 8,10,12]]

In [ ]:
col = np.array([[1],[2],[3]])

A = mat + col

similarly 
# sahpe of A (3,3)
# shape of col (1,3)

# of numpy broadcast of   [1,1,1],
#                         [2,2,2]
#                         [3,3,3]


### so the of the array will be 3x3 and the result will be

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]