Part 4: Indexing and Slicing 

Given the array: 
arr = np.array([[10, 20, 30, 40], 
                  [50, 60, 70, 80], 
                  [90, 100, 110, 120] 
]) 
1. Extract the second row. 
2. Extract the first two rows and the second two columns. 
3. Extract the last column using slicing. 
4. Replace the middle row with [1, 2, 3, 4].

In [1]:
import numpy as np

In [ ]:
arr = np.array([[10, 20, 30, 40], 
                  [50, 60, 70, 80], 
                  [90, 100, 110, 120] 
]) 



array([[10, 20, 30, 40]])

In [3]:
arr[1]

array([50, 60, 70, 80])

In [5]:
arr[0][1]

np.int64(20)

In [10]:
arr[2]

array([ 90, 100, 110, 120])

In [11]:
arr[1] = [1, 2, 3, 4]

In [12]:
arr

array([[ 10,  20,  30,  40],
       [  1,   2,   3,   4],
       [ 90, 100, 110, 120]])